format = """
[░▒▓](#d79921)\
[  ](bg:#d79921 fg:#090c0c)\
[](bg:#d65d0e fg:#d79921)\
$directory\
[](fg:#d65d0e bg:#cc241d)\
$git_branch\
$git_status\
[](fg:#cc241d bg:#282828)\
$nodejs\
$rust\
$golang\
$php\
$python\
[](fg:#282828 bg:#1d2021)\
$time\
[ ](fg:#1d2021)\
\n$character"""

[directory]
style = "fg:#ebdbb2 bg:#d65d0e"
format = "[ $path ]($style)"
truncation_length = 5
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#cc241d"
format = '[[ $symbol $branch ](fg:#ebdbb2 bg:#cc241d)]($style)'

[git_status]
style = "bg:#cc241d"
format = '[[($all_status$ahead_behind )](fg:#ebdbb2 bg:#cc241d)]($style)'

[nodejs]
symbol = ""
style = "bg:#282828"
format = '[[ $symbol ($version) ](fg:#ebdbb2 bg:#282828)]($style)'

[rust]
symbol = ""
style = "bg:#282828"
format = '[[ $symbol ($version) ](fg:#ebdbb2 bg:#282828)]($style)'

[golang]
symbol = ""
style = "bg:#282828"
format = '[[ $symbol ($version) ](fg:#ebdbb2 bg:#282828)]($style)'

[php]
symbol = ""
style = "bg:#282828"
format = '[[ $symbol ($version) ](fg:#ebdbb2 bg:#282828)]($style)'

[python]
symbol = ""
style = "bg:#282828"
format = '[[ $symbol ($version) ](fg:#ebdbb2 bg:#282828)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2021"
format = '[[  $time ](fg:#ebdbb2 bg:#1d2021)]($style)'
